/**
 * Auto-interp feature catalog for caiovicentino1/qwen36-27b-sae-papergrade.
 *
 * Generated by notebook 04b on 2026-04-25 with Claude Opus 4.7 via OpenRouter:
 *   1. Stream 5M tokens FineWeb-Edu through Qwen3.6-27B
 *   2. Pick top-500 most-active features per layer (L11/L31/L55)
 *   3. For each, capture top-20 32-token contexts where it fires strongest
 *   4. Send to Claude Opus 4.7 → short semantic label
 *
 * Stats:
 *   L11: 500 labels · 12 refusals · 4 polysemantic flags
 *   L31: 500 labels ·  8 refusals · 8 polysemantic flags
 *   L55: 500 labels ·  9 refusals · 5 polysemantic flags
 *
 * Bundled JSON lives next to this file (~85 KB raw, ~25 KB gzip).
 * Imported statically so SSR pages and client components both get synchronous
 * access without an extra fetch.
 *
 * Caveats:
 * - Labels are the LLM's hypothesis on top-20 contexts — not causally verified.
 * - Coverage is the top-500 most-active features per layer, NOT the 65k.
 *   Features that fire on rare patterns (e.g. our circuit-specific features)
 *   may not be labeled here.
 */

import catalogData from './feature-catalog.json'

interface CatalogShape {
  version: string
  model?: string
  sae_repo?: string
  layers?: number[]
  auto_interp_model?: string
  timestamp?: string
  labels: Record<string, Record<string, string>>
}

export const featureCatalog = catalogData as CatalogShape

/** Look up a feature's auto-interp label. Returns undefined if not in the
 * top-500 catalog for that layer. */
export function getFeatureLabel(layer: number | string, featureId: number | string): string | undefined {
  const layerKey = String(layer).replace(/^L/i, '')
  const featKey = String(featureId).replace(/^f/i, '')
  return featureCatalog.labels[layerKey]?.[featKey]
}

/** True if the catalog has a label for this feature (and it's not a refusal). */
export function hasFeatureLabel(layer: number | string, featureId: number | string): boolean {
  const label = getFeatureLabel(layer, featureId)
  return Boolean(label) && !label!.startsWith('(refused')
}

/** Total labeled features across all layers (for site stats). */
export const totalLabelCount = Object.values(featureCatalog.labels).reduce(
  (sum, m) => sum + Object.keys(m).length,
  0,
)
